Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"

  config.ssh.insert_key = true
  # config.ssh.insert_key = false
  # config.ssh.private_key_path = "/Users/charlmert/.ssh/id_rsa_vagrant"
  # config.vm.provision "file", source: "/Users/charlmert/.ssh/id_rsa_vagrant.pub", destination: "~/.ssh/authorized_keys"

  config.vm.network :forwarded_port, guest: 22, host: 2225, id: "ssh"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8081
  #config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.network "private_network", ip: "192.168.33.15"
  #config.vm.network "public_network", use_dhcp_assigned_default_route: true
  config.vm.network "public_network", ip: "11.0.0.15"
  config.vm.synced_folder ".", "/home/vagrant", type: 'nfs'
end
